# Generated by Django 6.0.2 on 2026-02-05 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("core", "0001_initial"),
        ("employees", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date du rendez-vous")),
                ("time", models.TimeField(verbose_name="Heure du rendez-vous")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Durée estimée du rendez-vous",
                        verbose_name="Durée (minutes)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmé"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("CANCELLED", "Annulé"),
                            ("NO_SHOW", "Absence"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Espèces, Mobile Money, etc.",
                        max_length=50,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="employees.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.salon",
                        verbose_name="Salon",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "db_table": "appointments",
                "ordering": ["-date", "-time"],
                "indexes": [
                    models.Index(
                        fields=["salon", "date", "status"],
                        name="appointment_salon_i_6cfbc2_idx",
                    ),
                    models.Index(
                        fields=["salon", "employee", "date"],
                        name="appointment_salon_i_7d7a3c_idx",
                    ),
                    models.Index(
                        fields=["salon", "client"],
                        name="appointment_salon_i_694ceb_idx",
                    ),
                ],
            },
        ),
    ]
