# Generated by Django 6.0.2 on 2026-02-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Visible sur le site public de réservation",
                verbose_name="Publié sur le site",
            ),
        ),
    ]
