# Generated by Django 6.0.2 on 2026-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="target",
            field=models.CharField(
                choices=[
                    ("homme", "Homme"),
                    ("femme", "Femme"),
                    ("enfant_fille", "Enfant (Fille)"),
                    ("enfant_garcon", "Enfant (Garçon)"),
                ],
                default="femme",
                help_text="À qui ce service est-il destiné ?",
                max_length=20,
                verbose_name="Cible",
            ),
        ),
    ]
