# Generated by Django 6.0.2 on 2026-02-05 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0003_service_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Image principale affichée dans les listes', null=True, upload_to='services/images/', verbose_name='Image principale'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('image', models.ImageField(help_text='Images de la galerie du service', upload_to='services/gallery/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text="Description de l'image pour l'accessibilité", max_length=255, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, help_text='Utilisée comme image de couverture', verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la galerie", verbose_name="Ordre d'affichage")),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.salon', verbose_name='Salon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Image de service',
                'verbose_name_plural': 'Images de services',
                'db_table': 'service_images',
                'ordering': ['service', 'order', 'id'],
                'indexes': [models.Index(fields=['salon', 'service'], name='service_ima_salon_i_7e97fc_idx'), models.Index(fields=['service', 'is_primary'], name='service_ima_service_f69513_idx')],
            },
        ),
    ]
