# Generated by Django 6.0.2 on 2026-02-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom du salon")),
                ("address", models.TextField(verbose_name="Adresse complète")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "opening_hours",
                    models.CharField(
                        default="8h00 - 18h00", max_length=100, verbose_name="Horaires"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Libreville",
                        max_length=50,
                        verbose_name="Fuseau horaire",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="salons/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#8b5a3c",
                        max_length=7,
                        verbose_name="Couleur principale",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Salon",
                "verbose_name_plural": "Salons",
                "db_table": "salons",
                "ordering": ["-created_at"],
            },
        ),
    ]
