# Generated by Django 6.0.2 on 2026-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug URL'),
        ),
    ]
