# Generated by Django 6.0.2 on 2026-02-06 14:22

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +241 0X XX XX XX XX (où X = 6 ou 7)', max_length=20, validators=[apps.core.validators.validate_gabon_phone], verbose_name='Téléphone'),
        ),
    ]
