# Generated by Django 6.0.2 on 2026-02-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_appointments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_view_all_appointments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_confirm_appointments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_start_appointments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_complete_appointments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_cancel_appointments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_reschedule_appointments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_move_appointments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_delete_appointments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_create_clients', models.BooleanField(blank=True, default=None, null=True)),
                ('can_view_clients', models.BooleanField(blank=True, default=None, null=True)),
                ('can_edit_clients', models.BooleanField(blank=True, default=None, null=True)),
                ('can_delete_clients', models.BooleanField(blank=True, default=None, null=True)),
                ('can_create_services', models.BooleanField(blank=True, default=None, null=True)),
                ('can_view_services', models.BooleanField(blank=True, default=None, null=True)),
                ('can_edit_services', models.BooleanField(blank=True, default=None, null=True)),
                ('can_delete_services', models.BooleanField(blank=True, default=None, null=True)),
                ('can_view_payments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_create_payments', models.BooleanField(blank=True, default=None, null=True)),
                ('can_view_employees', models.BooleanField(blank=True, default=None, null=True)),
                ('can_create_employees', models.BooleanField(blank=True, default=None, null=True)),
                ('can_edit_employees', models.BooleanField(blank=True, default=None, null=True)),
                ('can_delete_employees', models.BooleanField(blank=True, default=None, null=True)),
                ('can_edit_salon_settings', models.BooleanField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Permission Employé',
                'verbose_name_plural': 'Permissions Employés',
                'db_table': 'employee_permissions',
            },
        ),
    ]
