# Generated by Django 6.0.2 on 2026-02-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='can_edit_appointments',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_edit_employee_schedule',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_edit_salon_hours',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_edit_salon_info',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_export_appointments',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_export_clients',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_export_payments',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_manage_employee_permissions',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_refund_payments',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_send_client_messages',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='can_view_payment_reports',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
