# Generated by Django 6.0.2 on 2026-02-05 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("clients", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Espèces"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK_CARD", "Carte bancaire"),
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("OTHER", "Autre"),
                        ],
                        default="CASH",
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échoué"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de transaction pour Mobile Money, etc.",
                        max_length=100,
                        verbose_name="ID Transaction",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="appointments.appointment",
                        verbose_name="Rendez-vous",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.salon",
                        verbose_name="Salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "db_table": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["salon", "status"], name="payments_salon_i_2c7c4a_idx"
                    ),
                    models.Index(
                        fields=["salon", "payment_date"],
                        name="payments_salon_i_fdf6c5_idx",
                    ),
                    models.Index(
                        fields=["salon", "client"], name="payments_salon_i_c221b5_idx"
                    ),
                ],
            },
        ),
    ]
